import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getPitchStream } from "../lib/getPitchStream";
import { useState, useCallback, useEffect } from "react";
import * as tf from "@tensorflow/tfjs";

export default function Home() {
  const [model, setModel] = useState()
  useEffect(() => {
    tf.ready().then(() => {
      loadModel();
    });
  }, []);

  async function loadModel() {
    try {
      const model = await tf.loadGraphModel("spice/model.json");
      setModel(model)
    } catch (err) {
      console.log(err);
    }
  }

  function start() {
    getPitchStream(model);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => start()}>Analyse</button>
      </main>
    </div>
  );
}
